import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Study",
  description: "Generated by junstory",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1><Link href="/">WEB</Link></h1>
      <ol>
        <li><Link href="/read/1">html</Link></li>
        <li><Link href="/read/2">css</Link></li>
      </ol>
        {children}
        <ul>
          <li><a href="/create">Create</a></li>
          <li><a href="Update">Update</a></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      
      </body>
    </html>
  );
}
