import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Study",
  description: "Generated by junstory",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1><a href="/">WEB</a></h1>
      <ol>
        <li><a href="/read/1">html</a></li>
        <li><a href="/read/2">css</a></li>
      </ol>
        {children}
        <ul>
          <li><a href="/create">Create</a></li>
          <li><a href="Update">Update</a></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      
      </body>
    </html>
  );
}
